name: "Did Files Change"
description: "Check if specific files changed in a push"
branding:
  icon: "check-circle"
  color: "orange"
inputs:
  pathspec:
    description: "Pattern used to limit paths in the `git diff-tree` command."
    required: false
    default: ""
  sha:
    description: "The SHA of the commit to compare.  Defaults to current commit SHA."
    required: false
    default: ${{ github.sha }}
outputs:
  changed:
    description: "Whether or not files matched by the pathspec were changed."
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
    - ${{ inputs.sha }}
    - ${{ inputs.pathspec }}
